# -*- coding: utf-8 -*-
"""
Clearissa - Main Application Entry Point
-----------------------------------------
Data analysis, visualisation, and kinetic modelling platform.

Author: Križan Jurinović
Date: October 2025
"""

import logging
import os
import sys
import webbrowser
import multiprocessing

# Add resource_utils to path for resource resolution
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from resource_utils import get_log_dir, get_resource_path

# Force Qt binding selection BEFORE any other imports
# PyQtGraph will auto-detect and prefer PyQt6 if both PyQt5 and PyQt6 are
# installed. Since Clearissa uses PyQt5, we MUST force PyQtGraph to use
# PyQt5 to prevent fatal application crashes (exit code 0xC0000409).
#
# ============================================================================
os.environ['PYQTGRAPH_QT_LIB'] = 'PyQt5'

# Scientific libraries
import pandas as pd

# Configure matplotlib backend to use Qt5
import matplotlib
matplotlib.use('Qt5Agg')

# Apply Clearissa plotting style globally
from core.common.plot_style import apply_clearissa_style
apply_clearissa_style()

# PyQt5 GUI components
from PyQt5 import QtCore
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QApplication, QWidget, QTabWidget, QVBoxLayout
)

# PyQtGraph configuration
import pyqtgraph as pg

# Local module imports
from core.kinetics_processor import KineticsProcessor
from core.common.csv_data_loader import CSVDataLoader
from core.data_frame_processor.main import DataFrameProcessor
from core.common.options import OptionsPanel
from core.common.settings_manager import SettingsManager
from core.welcome_panel import WelcomePanel


def setup_logging():
    """
    Configure application-wide logging system.

    Creates log directory if needed and configures dual output to both
    file and console with consistent formatting.

    Handles both development and PyInstaller frozen environments.

    Returns
    -------
    None

    Notes
    -----
    Log file location:
    - Windows: C:\\Users\\<username>\\AppData\\Roaming\\Clearissa\\log\\clearissa.log
    - Linux/macOS: ~/.clearissa/log/clearissa.log

    Log level: INFO for both file and console handlers
    Format: timestamp - level - message
    """
    try:
        # Use resource_utils to get proper log directory
        log_dir = get_log_dir()
        log_file = log_dir / "clearissa.log"

        # Create formatter
        formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

        # Get root logger
        logger = logging.getLogger()
        logger.setLevel(logging.INFO)

        # Create file handler
        file_handler = logging.FileHandler(str(log_file), mode='a')
        file_handler.setLevel(logging.INFO)
        file_handler.setFormatter(formatter)

        # Create console handler
        console_handler = logging.StreamHandler()
        console_handler.setLevel(logging.INFO)
        console_handler.setFormatter(formatter)

        # Add both handlers to root logger
        logger.addHandler(file_handler)
        logger.addHandler(console_handler)

        print(f"Logging enabled - writing to {log_file} and console")
        logging.info("==================================================")
        logging.info("APPLICATION STARTED - CLEARISSA v%s", APP_VERSION)
        logging.info("Running mode: %s", "FROZEN (Compiled)" if getattr(sys, 'frozen', False) else "DEVELOPMENT")
        logging.info("==================================================")
    except Exception as e:
        print(f"Logging setup failed: {e} - continuing without logging")


def initialise_application_files():
    """
    Initialise required application files and directories.

    Creates default configuration files if they don't exist, preventing
    errors on first application startup.

    This includes:
    - Calibration data file (config/calibration_data.json)
    - Other configuration files as needed

    Returns
    -------
    None

    """
    try:
        # Initialise calibration file
        from core.convert_data_tab.calibration import ensure_calibration_file_exists
        calib_path = ensure_calibration_file_exists()
        logging.info(f"Calibration file ready at: {calib_path}")
    except Exception as e:
        logging.error(f"Failed to initialise calibration file: {e}")
        # Don't raise - allow app to continue even if calibration setup fails


"""
README:

Welcome to Clearissa, the data analysis simplification tool for the Tom Ouldridge research group.
This script efficiently extracts experiment names, timestamps, and fluorescence readings from 
raw data files generated by the ClarioStar plate reader, converting them into structured data 
for further analysis.

### Data Export Requirements:
- Ensure that the ClarioStar software exports the **raw dataset (NOT AVERAGES)** as a CSV file.
- Excel files (.xlsx, .xls) are also supported with the same structure.
- If multiple CSV files originate from the same experimental run, they must be stored in the 
  same directory for proper processing.

### Usage Instructions:
- The CSV file must have a specific structure (detailed in File Format Guide).
- Users must select the folder containing the CSV files.
- The header of the CSV file is essential for extracting experiment tags and timestamps.
- The cell containing **"Well"** acts as a structural boundary for building the DataFrame.

### Merging Multiple Files:
- **Files can be merged only if they contain explicit timestamps.** If timestamps are absent 
  from the headers, the script assumes all files start at time **0**.  
- If multiple files without timestamps contain identical column headers, their data will be 
  **overwritten** instead of merged correctly.

For detailed format information, click "File Format Guide" in the application.

================= KNOWN ISSUES ===================

- High-resolution monitors (e.g. 4K) may display the pyqtgraph axes incorrectly—take extra care!
  Check the first two lines before the qtapp initialisation to adjust the scaling.

==================================================

For reporting errors and feedback, contact k.jurinovic22@ic.ac.uk

==================================================================================================================
  Code is working in the specified environment. Other Python versions may cause unexpected behaviour.

  Python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
  NumPy version: 1.26.x
  Pandas version: 2.1.x
  Matplotlib version: 3.8.x
  Scipy version: 1.11.x
==================================================================================================================
"""

# Configure pandas display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pg.setConfigOptions(antialias=True)

# Application constants
APP_NAME = "Clearissa"
APP_VERSION = "1.713"
# Application


class MainApplication(QTabWidget):
    """Main application window with tabbed interface for data analysis tools."""

    def __init__(self):
        super().__init__()
        self._setup_window()
        self._initialise_components()
        self._create_tabs()
        self._apply_styling()
        self._connect_signals()
        # Don't populate manual on startup—only when tab is accessed

    def _setup_window(self):
        """Configure main window properties and tab change tracking."""
        self.setWindowTitle(APP_NAME)
        self.setMinimumSize(1200, 720)
        self.setTabPosition(QTabWidget.North)
        self.previous_tab_index = None
        self.currentChanged.connect(self.on_tab_changed)

    def _initialise_components(self):
        """Initialise core application components and establish inter-component references."""
        self.settings_manager = SettingsManager()
        self.optionsproc = OptionsPanel()
        self.data_loader = CSVDataLoader(self)
        self.dataproc = DataFrameProcessor(self, self.data_loader, self.optionsproc)
        self.data_loader.dataproc = self.dataproc
        self.kineticproc = None  # Created on demand

    def _create_tabs(self):
        """Create and configure all application tabs."""
        self._create_main_tab()
        # Don't create View Data tab initially—it will be created when needed
        self._create_options_tab()

        # Store reference for lazy tab creation
        self.view_data_tab = None

    def _create_main_tab(self):
        """Create the main landing tab using WelcomePanel."""
        self.welcome_panel = WelcomePanel(APP_VERSION)
        self.addTab(self.welcome_panel, "Main")

    def _connect_signals(self):
        """Connect signals from welcome panel to their respective handlers."""
        self.welcome_panel.load_folder_clicked.connect(self.data_loader.load_csv_folder)
        self.welcome_panel.view_data_clicked.connect(self.switch_to_view_data_tab)
        self.welcome_panel.kinetics_clicked.connect(self.switch_to_kinetics_tab)
        self.welcome_panel.manual_clicked.connect(self.open_manual)
        self.welcome_panel.options_clicked.connect(self.switch_to_options_tab)

    def _create_view_data_tab(self):
        """Create the data viewing tab on demand."""
        if self.view_data_tab is None:
            self.view_data_tab = QWidget()
            self.view_data_layout = QVBoxLayout(self.view_data_tab)
            self.addTab(self.view_data_tab, "View Data")


    def _create_options_tab(self):
        """Create the options configuration tab."""
        self.options_tab = QWidget()
        options_layout = QVBoxLayout(self.options_tab)
        options_layout.addWidget(self.optionsproc)
        self.addTab(self.options_tab, "Options")

    def _apply_styling(self):
        """Apply custom CSS styling to the tab widget."""
        self.setStyleSheet("""
            QTabWidget::pane {
                border: 1px solid #9E9E9E;
                top: -1px;
            }
            QTabBar::tab {
                background-color: #E0E0E0;
                border: 1px solid #9E9E9E;
                border-top-left-radius: 4px;
                border-top-right-radius: 4px;
                padding: 6px 12px;
                color: #212121;
            }
            QTabBar::tab:selected {
                background-color: #BDBDBD;
                border-bottom-color: #BDBDBD;
                color: #212121;
            }
            QTabBar::tab:!selected {
                margin-top: 2px;
            }
        """)

    def switch_to_options_tab(self):
        """Switch to the options configuration tab."""
        self.setCurrentWidget(self.options_tab)

    def switch_to_view_data_tab(self):
        """Switch to the data viewing tab and initialise the data window if needed."""
        self._create_view_data_tab()  # Create if doesn't exist
        self.setCurrentWidget(self.view_data_tab)
        # Only initialise if the tab is empty
        if self.view_data_layout.count() == 0:
            self.dataproc.view_data_window()

    def switch_to_kinetics_tab(self):
        """Switch to the kinetics analysis tab, creating it if necessary."""
        # Clean up existing kinetics tab if present
        if hasattr(self, 'kinetics_tab') and self.indexOf(self.kinetics_tab) != -1:
            if self.kineticproc is not None:
                self.kinetics_tab.layout().removeWidget(self.kineticproc)
                self.kineticproc.deleteLater()
                self.kineticproc = None
            self.removeTab(self.indexOf(self.kinetics_tab))

        # Create new kinetics tab
        self.kinetics_tab = QWidget()
        kinetics_layout = QVBoxLayout(self.kinetics_tab)
        self.kineticproc = KineticsProcessor()
        self.kineticproc.init_ui()  # Initialise UI before adding to layout
        
        # Automatically restore last saved state
        self.kineticproc.restore_state()
        
        kinetics_layout.addWidget(self.kineticproc)
        self.addTab(self.kinetics_tab, "Kinetics")
        self.setCurrentWidget(self.kinetics_tab)


    def open_manual(self):
        """
        Open the user manual HTML file in the system's default web browser.

        Handles both development and PyInstaller frozen environments.
        """
        try:
            manual_path = get_resource_path("manual.html")

            # Convert to absolute path and use file:// URL
            manual_path = os.path.abspath(manual_path)

            # Check if file exists
            if not os.path.exists(manual_path):
                logging.error(f"Manual file not found at: {manual_path}")
                from PyQt5.QtWidgets import QMessageBox
                QMessageBox.warning(
                    self,
                    "Manual Not Found",
                    f"The user manual file could not be found at:\n{manual_path}"
                )
                return

            # Open in default browser
            # Use file:/// protocol (three slashes for absolute paths on Windows)
            if sys.platform == 'win32':
                # Windows requires special handling for file URLs
                file_url = f"file:///{manual_path.replace(os.sep, '/')}"
            else:
                file_url = f"file://{manual_path}"

            webbrowser.open(file_url)
            logging.info(f"Opened manual in browser: {manual_path}")

        except Exception as e:
            logging.error(f"Failed to open manual: {e}")
            from PyQt5.QtWidgets import QMessageBox
            QMessageBox.critical(
                self,
                "Error Opening Manual",
                f"Failed to open the user manual:\n{str(e)}"
            )

    def on_tab_changed(self, new_index):
        """Handle tab change events and save state of previous tab if applicable."""
        if self.previous_tab_index is not None:
            previous_tab = self.widget(self.previous_tab_index)
            if hasattr(previous_tab, "save_state"):
                previous_tab.save_state()
            # Save kinetics processor state when switching away from it
            if hasattr(self, 'kineticproc') and self.kineticproc is not None:
                if previous_tab == self.kinetics_tab:
                    self.kineticproc.save_state()
            # Save dataprocessor state when switching away from View Data tab
            if hasattr(self, 'dataproc') and self.dataproc is not None:
                if hasattr(self, 'view_data_tab') and previous_tab == self.view_data_tab:
                    self.dataproc.save_state()
        self.previous_tab_index = new_index

    def closeEvent(self, event):
        """Handle application closure by saving all tab states."""
        # Save data processor state
        if hasattr(self, 'dataproc') and self.dataproc is not None:
            self.dataproc.save_state()

        # Save kinetics processor state if it exists
        if hasattr(self, 'kineticproc') and self.kineticproc is not None:
            self.kineticproc.save_state()

        # Save state for all tabs that support it
        for index in range(self.count()):
            tab = self.widget(index)
            if hasattr(tab, "save_state"):
                tab.save_state()

        super().closeEvent(event)


if __name__ == "__main__":
    # CRITICAL: Enable multiprocessing support in frozen executables (PyInstaller)
    # This prevents multiple application instances from spawning when using
    # ProcessPoolExecutor in the kinetics fitting worker
    multiprocessing.freeze_support()

    # Initialise logging
    setup_logging()

    # Initialise application files (calibration, config, etc.)
    initialise_application_files()

    # Configure high DPI display support
    QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

    # Create and run application
    app = QApplication(sys.argv)
    window = MainApplication()
    window.show()
    sys.exit(app.exec_())
